version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vms-pro-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    networks:
      - vms-network

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: vehicle_service_system
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - vms-network

networks:
  vms-network:
    driver: bridge

volumes:
  mysql-data:
